/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    VitoTable: typeof import('./src/components/VitoTable.vue')['default']
    VitoTableV2: typeof import('./src/components/VitoTableV2.vue')['default']
    VtCell: typeof import('./src/components/cells/VtCell.vue')['default']
    VtColumnSelector: typeof import('./src/components/VtColumnSelector.vue')['default']
    VtDatetimeFilter: typeof import('./src/components/filters/VtDatetimeFilter.vue')['default']
    VtDatetimeFilterMore: typeof import('./src/components/filters/VtDatetimeFilterMore.vue')['default']
    VtExportDialog: typeof import('./src/components/exports/VtExportDialog.vue')['default']
    VtHeaderFilter: typeof import('./src/components/filters/VtHeaderFilter.vue')['default']
    VtNumberFilter: typeof import('./src/components/filters/VtNumberFilter.vue')['default']
    VtNumberFilterMore: typeof import('./src/components/filters/VtNumberFilterMore.vue')['default']
    VtSelect: typeof import('./src/components/VtSelect.vue')['default']
    VtSelectCell: typeof import('./src/components/cells/VtSelectCell.vue')['default']
    VtSelectFilter: typeof import('./src/components/filters/VtSelectFilter.vue')['default']
    VtStringFilter: typeof import('./src/components/filters/VtStringFilter.vue')['default']
    VtStringFilterMore: typeof import('./src/components/filters/VtStringFilterMore.vue')['default']
    VtTableDialog: typeof import('./src/components/VtTableDialog.vue')['default']
    VtTimeFilter: typeof import('./src/components/filters/VtTimeFilter.vue')['default']
    VtTimeFilterMore: typeof import('./src/components/filters/VtTimeFilterMore.vue')['default']
    VtTransfer: typeof import('./src/components/VtTransfer.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
